repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.3.2", "prettier-plugin-organize-imports@3.2.4"]
        files: '(frontend|libs/shared-ts)/.*\.(ts|tsx|js|jsx|json|css|md)'
  - repo: https://github.com/eslint/eslint
    rev: v9.7.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@9.7.0
          - '@typescript-eslint/parser@7.16.1'
          - '@typescript-eslint/eslint-plugin@7.16.1'
          - eslint-config-prettier@9.1.0
          - eslint-plugin-import@2.29.1
          - typescript@5.4.5
        files: '(frontend|libs/shared-ts)/.*\.(ts|tsx|js|jsx)'
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.14.0
    hooks:
      - id: markdownlint-cli2
        files: '.*\.md$'
