services:
  gateway:
    image: kong:3.6
    container_name: su-gateway
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: info
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./gateway/kong.yml:/kong/kong.yml:ro
    ports:
      - "8000:8000"  # proxy
      - "8008:8001"  # admin (host 8008)
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8001/status >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      auth-service:
        condition: service_healthy
      device-service:
        condition: service_healthy
      command-service:
        condition: service_healthy
      data-ingest-service:
        condition: service_healthy
      analytics-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
