# Local development scaffold for SystemUpdate-Web (M0)
# NOTE: Service definitions are minimal and may be extended in M1+.

services:
  postgres:
    image: postgres:15-alpine
    container_name: su-postgres
    environment:
      POSTGRES_USER: systemupdate
      POSTGRES_PASSWORD: systemupdate
      POSTGRES_DB: systemupdate
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: su-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

  auth-service:
    build: ./services/auth-service
    container_name: su-auth
    environment:
      PORT: 8001
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  ws-hub:
    build: ./services/ws-hub
    container_name: su-ws-hub
    environment:
      PORT: 8002
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002"]
    ports:
      - "8002:8002"
    restart: unless-stopped
    depends_on:
      - redis

  device-service:
    build: ./services/device-service
    container_name: su-device
    environment:
      PORT: 8003
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8003"]
    ports:
      - "8003:8003"
    restart: unless-stopped
    depends_on:
      - postgres

#  gateway:
#    image: kong:3.6
#    # Configure declarative config and DB-less mode in M1

volumes:
  pgdata:
  minio:
