# Production-like override: use secure Kong gateway by default.

services:
  # Enable secure gateway without compose profile in prod
  gateway-secure:
    # Override ports to only publish proxy on 80
    ports:
      - "80:8000"     # publish proxy on port 80
    # Do not publish or bind admin in prod
    environment:
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_ADMIN_LISTEN: off
    # Remove runtime dependencies so gateway can start standalone for smoke tests
    depends_on: {}

  # Optionally disable exposing service ports directly in prod
  auth-service:
    ports: []
  device-service:
    ports: []
  command-service:
    ports: []
  data-ingest-service:
    ports: []
  analytics-service:
    ports: []
  notification-service:
    ports: []
    depends_on: {}
  ws-hub:
    ports: []

  # Stub to satisfy compose validation for services depending on otel-collector
  otel-collector:
    image: otel/opentelemetry-collector:0.95.0
    # no ports; no additional config; won't start when only gateway-secure is brought up
