apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Tempo
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap: true
      nodeGraph: true
      tracesToLogsV2:
        datasourceUid: prometheus
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - { key: 'service.name', value: 'service' }
        queries:
          - name: 'Latency'
            query: 'histogram_quantile(0.9, sum(rate(http_server_request_duration_seconds_bucket{service_name=~"$__service"}[5m])) by (le))'
