route:
  receiver: webhooks
  group_by: ['alertname', 'service_name']
  group_interval: 30s
  repeat_interval: 4h

receivers:
  - name: webhooks
    webhook_configs:
      - url: 'http://notification-service:8007/alerts'
  - name: dev-null

# Examples to enable later:
#  - name: webhooks
#    webhook_configs:
#      - url: 'http://host.docker.internal:5001/alerts'
#  - name: email
#    email_configs:
#      - to: 'ops@example.com'
#        from: 'alertmanager@example.com'
#        smarthost: 'smtp.example.com:587'
#        auth_username: 'alertuser'
#        auth_password: 'changeme'
