receivers:
  otlp:
    protocols:
      http:
      grpc:

connectors:
  spanmetrics:
    dimensions:
      - service.name
      - status_code
      - http.method
      - http.route
      - http.status_code
    namespace: traces_spanmetrics
    histogram:
      explicit:
        buckets: [1ms, 2ms, 5ms, 10ms, 20ms, 50ms, 100ms, 200ms, 500ms, 1s, 2s, 5s]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

exporters:
  logging:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:8889
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/tempo, spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      exporters: [logging]
