http:
  routers:
    auth:
      entryPoints: ["web"]
      rule: "PathPrefix(`/api/auth`)"
      service: auth
    device:
      entryPoints: ["web"]
      rule: "PathPrefix(`/api/device`)"
      service: device
    ws_hub:
      entryPoints: ["web"]
      rule: "PathPrefix(`/ws`)"
      service: ws_hub
    command:
      entryPoints: ["web"]
      rule: "PathPrefix(`/api/command`)"
      service: command
    ingest:
      entryPoints: ["web"]
      rule: "PathPrefix(`/api/ingest`)"
      service: ingest
    analytics:
      entryPoints: ["web"]
      rule: "PathPrefix(`/api/analytics`)"
      service: analytics

  services:
    auth:
      loadBalancer:
        servers:
          - url: "http://auth-service:8001"
    device:
      loadBalancer:
        servers:
          - url: "http://device-service:8003"
    ws_hub:
      loadBalancer:
        servers:
          - url: "http://ws-hub:8002"
    command:
      loadBalancer:
        servers:
          - url: "http://command-service:8004"
    ingest:
      loadBalancer:
        servers:
          - url: "http://data-ingest-service:8005"
    analytics:
      loadBalancer:
        servers:
          - url: "http://analytics-service:8006"
