global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'sample-consumer'
    static_configs:
      - targets: ['sample-consumer:9000']
