name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pytest-asyncio httpx schemathesis testcontainers psycopg2-binary redis
      - name: Lint (ruff)
        run: |
          ruff --version || true
          ruff . || true
      - name: Auth service tests
        working-directory: services/auth-service
        run: |
          pip install -r requirements.txt
          pytest -q
      - name: Auth service contract tests (Schemathesis)
        working-directory: services/auth-service
        run: |
          pytest -q -k contract
      - name: WS hub tests
        working-directory: services/ws-hub
        run: |
          pip install -r requirements.txt
          pytest -q
      - name: Device service tests
        working-directory: services/device-service
        run: |
          pip install -r requirements.txt
          pytest -q
      - name: Device service contract tests (Schemathesis)
        working-directory: services/device-service
        run: |
          pytest -q -k contract

  frontend-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies (placeholder)
        run: |
          echo "No frontend yet"

  sbom-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate SBOM (Syft)
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
      - name: Vulnerability Scan (Trivy)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          exit-code: '0'
