name: OPA Deny E2E (Gateway-Secure)

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'docker-compose.yml'
      - 'docker-compose.prod.yml'
      - 'docker-compose.smoke.yml'
      - 'gateway/**'
      - 'services/**'
      - 'tests/e2e/**'
      - '.github/workflows/opa-deny-e2e-secure.yml'

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create CI override (enable OPA on command-service & map secure gateway to 8080)
        run: |
          cat > ci.secure.yml <<'YAML'
          services:
            command-service:
              environment:
                OPA_REQUIRED: "1"
                OPA_URL: "http://opa:8181/v1/data/systemupdate/allow"
            gateway-secure:
              ports:
                - "8080:8000"
              environment:
                KONG_ADMIN_LISTEN: off
              depends_on: {}
          YAML

      - name: Start minimal stack + OPA + gateway-secure
        run: |
          docker compose -f docker-compose.yml -f docker-compose.prod.yml -f ci.secure.yml up -d postgres redis opa command-service gateway-secure

      - name: Wait for services
        run: |
          for i in {1..60}; do curl -fsS http://localhost:8004/healthz && break || sleep 2; done
          for i in {1..60}; do code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080); [[ "$code" == "200" || "$code" == "404" ]] && break || sleep 2; done
          for i in {1..60}; do curl -fsS http://localhost:8181/health && break || sleep 2; done

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Playwright deps
        working-directory: systemupdate-web/tests/e2e
        run: |
          npm ci || npm install
          npx playwright install --with-deps chromium

      - name: Run OPA deny E2E via gateway-secure
        working-directory: systemupdate-web/tests/e2e
        env:
          OPA_E2E: "1"
          GATEWAY_URL: "http://localhost:8080"
        run: |
          npx playwright test tests/opa-deny.spec.ts --reporter=dot

      - name: Teardown
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml -f ci.secure.yml down -v
