name: Python Lint (ruff)

on:
  push:
    paths:
      - 'services/**'
      - '.github/workflows/python-lint.yml'
  pull_request:
    paths:
      - 'services/**'
      - '.github/workflows/python-lint.yml'

jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install ruff
        run: pipx install ruff
      - name: Run ruff
        working-directory: systemupdate-web
        run: |
          ruff --version
          # Lint all Python in services/ and scripts/
          ruff check services scripts || (echo "Run ruff --fix locally to auto-fix" && exit 1)
