name: SBOM and Security Scan

on:
  push:
    paths:
      - 'systemupdate-web/**'
  pull_request:
    paths:
      - 'systemupdate-web/**'

jobs:
  scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: systemupdate-web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft version

      - name: Generate SBOM (SPDX JSON)
        run: |
          syft packages dir:. -o spdx-json > sbom.spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-spdx
          path: systemupdate-web/sbom.spdx.json

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y trivy
          trivy --version

      - name: Trivy filesystem scan (vulns + secrets)
        run: |
          trivy fs --no-progress --scanners vuln,secret --severity HIGH,CRITICAL --exit-code 1 .

      - name: Upload Trivy results (optional SARIF step placeholder)
        if: always()
        run: echo "Trivy scan completed."
