name: TypeScript Lint

on:
  push:
    paths:
      - 'libs/shared-ts/**'
      - '.github/workflows/ts-lint.yml'
  pull_request:
    paths:
      - 'libs/shared-ts/**'
      - '.github/workflows/ts-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libs/shared-ts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript Typecheck
        run: npm run typecheck

      - name: ESLint
        run: npm run lint

      - name: Prettier Check
        run: npm run format:check
